const test = require('node:test');
const assert = require('node:assert/strict');
global.Script = { name: () => 'MF885 Test' };
const app = require('../scriptable.js');

function model(tab='sms') { return {tab,loadedAt:Date.now(),sms:{messages:[{id:'1',phone:'+1',date:'now',content:'hello'}],loading:true},errors:{},network:{},battery:{},traffic:{},cellularDiagnostics:{},ussd:{state:'unchecked',detail:'Not checked'},deviceAccess:{state:'unchecked',detail:'Not checked',capabilities:[]},cellularControl:{state:'unchecked',detail:'Not checked'}}; }

test('initial HTML is immediately useful and marks history as loading',()=>{const html=app.buildHtml(model());assert.match(html,/hello/);assert.match(html,/Loading message history…/);assert.match(html,/Not checked/);assert.match(html,/data-detect="ussd"/);});
test('SMS and router models render a non-empty main with the requested active tab',()=>{for(const tab of ['sms','router']){const html=app.buildHtml(model(tab));const main=html.match(/<main>([\s\S]*?)<\/main>/i);assert.ok(main&&main[1].trim(),`${tab} main must not be empty`);assert.match(html,new RegExp(`<section id="${tab}" class="tab active"`));}});
test('dashboard has a readiness marker and native Alert fallback for WebView failures',()=>{const source=require('node:fs').readFileSync(require.resolve('../scriptable.js'),'utf8');assert.match(source,/dataset\.zmiReady\s*=\s*'true'/);assert.match(source,/WebView loadHTML stage failed/);assert.match(source,/WebView present stage failed/);const fallback=source.match(/async function showMessage[\s\S]*?\n}/);assert.ok(fallback);assert.match(fallback[0],/new Alert\(\)/);assert.doesNotMatch(fallback[0],/new WebView\(\)/);});
test('client applies complete and partial SMS history without document reload',()=>{const js=app.clientScript(model());assert.match(js,/window\.zmiApplySmsHistory=function/);assert.match(js,/payload\.warning/);assert.match(js,/Message history is incomplete|⚠️/);assert.doesNotMatch(js,/location\.(?:href|assign|replace)|location\s*=/);});
test('document has no Scriptable relaunch links',()=>{const text=app.buildHtml(model())+app.clientScript(model());assert.doesNotMatch(text,/scriptable:\/\/\/run|This action will reopen|runUrl|navigationInProgress/);});
test('client exposes targeted status, capability and action updates',()=>{const js=app.clientScript(model());for(const name of ['zmiApplyStatus','zmiApplySmsHistory','zmiApplyCapability','zmiApplyActionResult'])assert.match(js,new RegExp('window\\.'+name));assert.match(js,/CustomEvent\('ZMICommand'/);});
test('tab, scroll and unsent SMS draft survive DOM updates',()=>{const js=app.clientScript(model());assert.match(js,/zmiTab/);assert.match(js,/zmiScrollY/);assert.match(js,/zmiSmsDraft/);assert.match(js,/window\.scrollTo/);});
test('SMS pages merge with deduplication',()=>{let r={messages:[],loadedPages:0,totalPages:null,totalMessages:null};app.mergeSmsPage(r,{page:1,totalPages:2,totalMessages:2,messages:[{id:'1',phone:'a',date:'d',content:'x'}]});app.mergeSmsPage(r,{page:2,messages:[{id:'1',phone:'a',date:'d',content:'x'},{id:'2',phone:'b',date:'d',content:'y'}]});assert.deepEqual(r.messages.map(x=>x.id),['1','2']);assert.equal(r.loadedPages,2);});
test('in-flight guard shares concurrent operation',async()=>{const guard=app.createInFlightGuard();let calls=0,release;const gate=new Promise(r=>release=r);const a=guard.run(async()=>{calls++;await gate;return 7});const b=guard.run(async()=>{calls++;return 8});assert.equal(a,b);release();assert.equal(await b,7);assert.equal(calls,1);});
test('capability cache keeps positives and expires negative entries after 24 hours',()=>{const now=Date.now(),base={schema:1,host:'router',checkedAt:now};assert.equal(app.capabilityCacheValid({...base,positive:true},'router',now+99*86400000),true);assert.equal(app.capabilityCacheValid({...base,positive:false},'router',now+23*3600000),true);assert.equal(app.capabilityCacheValid({...base,positive:false},'router',now+25*3600000),false);assert.equal(app.capabilityCacheValid({...base,positive:true,schema:2},'router',now),false);});
test('dispatcher whitelists actions, validates parameters and correlates ids',async()=>{const replies=[];const dispatch=app.createWebViewDispatcher({refresh:async()=>({fresh:true}),sendSms:async p=>p.text},r=>replies.push(r));assert.equal((await dispatch({id:'one',action:'refresh',params:{}})).id,'one');assert.equal((await dispatch({id:'two',action:'sendSms',params:{to:'+1',text:'hi'}})).result,'hi');assert.equal((await dispatch({id:'bad',action:'arbitraryFunction',params:{}})).ok,false);assert.deepEqual(replies.map(x=>x.id),['one','two','bad']);});
test('dispatcher requires danger confirmation and converts handler errors',async()=>{let called=0;const dispatch=app.createWebViewDispatcher({reboot:async()=>{called++;return 'ok'},refresh:async()=>{throw new Error('offline')} });assert.equal((await dispatch({id:'a',action:'reboot',params:{}})).ok,false);assert.equal(called,0);assert.equal((await dispatch({id:'b',action:'reboot',params:{confirmed:true}})).ok,true);const failed=await dispatch({id:'c',action:'refresh',params:{}});assert.equal(failed.ok,false);assert.equal(failed.error,'offline');});
test('arbitrary function names can never be selected by WebView data',()=>{assert.throws(()=>app.validateWebViewCommand({id:'x',action:'constructor',params:{}}),/not allowed/);assert.throws(()=>app.validateWebViewCommand({id:'x',action:'cellularMode',params:{mode:'evil',confirmed:true}}),/Invalid cellular mode/);});
